apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: voter-api
  labels:
    app: voter
  name: voter
spec:
  replicas: 3
  strategy: {}
  template:
    metadata:
      labels:
        app: voter
        version: v1
    spec:
      containers:
      - image: garystafford/voter-service:gke-0.6.261
        name: voter
        ports:
        - containerPort: 8080
        # readinessProbe:
        #   httpGet:
        #     path: /voter/health
        #     port: 8080
        #     scheme: HTTP
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 1
        #   periodSeconds: 15
        # livenessProbe:
        #   httpGet:
        #     path: /voter/health
        #     port: 8080
        #     scheme: HTTP
        #   initialDelaySeconds: 15
        #   timeoutSeconds: 1
        #   periodSeconds: 15
        env:
          - name: SPRING_RABBITMQ_HOST
            valueFrom:
              secretKeyRef:
                name: rabbitmq-connection-string
                key: host
          - name: SPRING_RABBITMQ_VIRTUAL_HOST
            valueFrom:
              secretKeyRef:
                name: rabbitmq-connection-string
                key: virtualHost
          - name: SPRING_RABBITMQ_USERNAME
            valueFrom:
              secretKeyRef:
                name: rabbitmq-connection-string
                key: username
          - name: SPRING_RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-connection-string
                key: password
          - name: SPRING_DATA_MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: mongodb-atlas-voter
                key: connection-string
        command: ["/bin/sh"]
        args: ["-c", "java -Dspring.profiles.active=kub-aks -Djava.security.egd=file:/dev/./urandom -jar /voter/voter-service.jar"]
        imagePullPolicy: Always
      restartPolicy: Always
status: {}
