apiVersion: v1
kind: Secret
metadata:
  name: istio-ingress-certs
  namespace: istio-system
type: kubernetes.io/tls
data:
  tls.crt: <base64-encoded-string-goes-here>
  tls.key: <base64-encoded-string-goes-here>
